In [18]:
%pip install spacy

Requirement already satisfied: spacy in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (0.27.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (4.70.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (2.34.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (83.0.0)
Requirement already satisfied: packaging>=20.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (26.3)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (3.5.1)
Requirement already satisfied: numpy>=1.19.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy) (1.26.4)
Requirement already satisfied: annotated-types>=0.6.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.7.22)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.1.5)
Requirement already satisfied: shellingham>=1.3.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.5)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.24.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.24.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (2.3.0)
Requirement already satisfied: mdurl~=0.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [19]:
%pip install scispacy

Requirement already satisfied: scispacy in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (0.6.2)
Requirement already satisfied: spacy<3.9.0,>=3.7.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (3.7.5)
Requirement already satisfied: scipy in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (1.17.1)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (2.34.2)
Requirement already satisfied: conllu in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (6.0.0)
Requirement already satisfied: numpy<2.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (1.26.4)
Requirement already satisfied: joblib in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (1.5.3)
Requirement already satisfied: nmslib-metabrainz==2.1.3 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (2.1.3)
Requirement already satisfied: scikit-learn>=0.20.3 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (1.9.0)
Requirement already satisfied: pysbd in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scispacy) (0.3.4)
Requirement already satisfied: pybind11>=2.2.3 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from nmslib-metabrainz==2.1.3->scispacy) (3.1.0)
Requirement already satisfied: psutil in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from nmslib-metabrainz==2.1.3->scispacy) (7.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->scispacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->scispacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->scispacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->scispacy) (2026.7.22)
Requirement already satisfied: narwhals>=2.0.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scikit-learn>=0.20.3->scispacy) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from scikit-learn>=0.20.3->scispacy) (3.6.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.0.13)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (0.4.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (0.27.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (4.70.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.13.4)
Requirement already satisfied: jinja2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.1.6)
Requirement already satisfied: setuptools in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (83.0.0)
Requirement already satisfied: packaging>=20.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (26.3)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.9.0,>=3.7.0->scispacy) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.9.0,>=3.7.0->scispacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.9.0,>=3.7.0->scispacy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.9.0,>=3.7.0->scispacy) (0.4.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.9.0,>=3.7.0->scispacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.9.0,>=3.7.0->scispacy) (0.1.5)
Requirement already satisfied: shellingham>=1.3.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (0.0.5)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.9.0,>=3.7.0->scispacy) (0.24.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.9.0,>=3.7.0->scispacy) (0.24.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.9.0,>=3.7.0->scispacy) (7.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from jinja2->spacy<3.9.0,>=3.7.0->scispacy) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (2.20.0)
Requirement already satisfied: wrapt in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.9.0,>=3.7.0->scispacy) (2.3.0)
Requirement already satisfied: mdurl~=0.1 in /home/exouser/Desktop/bridge-rna/.venv-1/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [20]:
#imports
import spacy
import scispacy
import timeit
import pandas as pd
import os
from pathlib import Path
from collections import defaultdict
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter
import plotly.express as px

In [21]:
#load term parser
nlp = spacy.load("en_core_sci_lg")

In [44]:
#change this to live file ingest later
vectorizer = CountVectorizer(lowercase=True,)
file_path = Path.cwd().parent / "archs4metadata/COHORT|study=OSD-770|spaceflight=Space Flight_hits.csv"

#md_df = pd.read_parquet(file_path) if file_path.suffix == ".parquet" else pd.read_csv(file_path)
md_df = pd.read_csv(file_path)

idx = defaultdict(set) #may want to cache later if it gets big

In [45]:
def _add_spacy_terms(): # adds spacy terms to dataframe, returns list of flat terms
    md_df['spacey_terms'] = md_df.apply(lambda _: [], axis=1)

    for row in md_df.itertuples():
        doc = nlp(row.geo_summary)
        for ent in doc.ents:
            term = ent.text.split()
            row.spacey_terms.extend(term)
            for t in term:
                idx[t].add(row.gse)
            
    
    return [item for lst in md_df["spacey_terms"] for item in lst]

In [46]:
def _update_idx():
    
    analyzer = vectorizer.build_analyzer()
    new_idx = defaultdict(set)

    for term,doc_ids in idx.items():
        tokenized = analyzer(term)
        for token in tokenized:
            new_idx[token].update(doc_ids)

    return new_idx

In [47]:
def _add_journals(cl_df):
     cl_df['journals'] = cl_df.apply(lambda _: [], axis=1)
     cl_df["Representation"] = cl_df["Representation"].apply(lambda lst: [x for x in lst if x])

     for row in cl_df.itertuples():
        
        
        for term in row.Representation:
            
            if term in idx:
               row.journals.extend(list(idx[term]))
            else:
                  print(f"term {term} not found in index")
     
     return cl_df

In [48]:

def cluster_sample(): 
    global idx
    flat_terms = _add_spacy_terms()
    vectorizer.fit(flat_terms)
    idx = _update_idx()
    model = SentenceTransformer('allenai/biomed_roberta_base')
    topic_model = BERTopic(vectorizer_model=vectorizer, embedding_model=model)
    topics,probs = topic_model.fit_transform(flat_terms)
    clusters = _add_journals(topic_model.get_topic_info())   
    return topic_model,clusters

In [49]:
def get_cluster_distribution(clusters,cluster_idx):
    journals = clusters.iloc[cluster_idx].journals
    cnts = Counter(journals)
   
    total = len(journals)

    percent_dist =  {name: (count / total) * 100 for name, count in cnts.items()}
    return percent_dist

In [50]:
def get_cluster_counts(clusters,cluster_idx):
    journals = clusters.iloc[cluster_idx].journals
    cnts = Counter(journals)
    cnts = dict(cnts)
    return cnts

In [51]:
def get_top_cluster_distribution(clusters,n=5):
    top_clusters = clusters.head(n)
    distributions = {}
    for idx, row in top_clusters.iterrows():
        distributions[row.Topic] = get_cluster_distribution(clusters,idx)
    return distributions

In [52]:
def get_top_journals(clusters,n=5):
    
    top_clusters = clusters.head(n).iloc[1:] #skip outliers
    overall_cnts = defaultdict(int)
    for idx, row in top_clusters.iterrows():
       # print(f"Processing cluster {row.Topic} at index {idx}")
        journal_counts = get_cluster_counts(clusters,idx)
       # print(f"Journal counts for cluster {row.Topic}: {journal_counts}")
        for journal, count in journal_counts.items():
            #print(f"Adding {count} to overall count for journal {journal}")
            overall_cnts[journal] += count
    
    return overall_cnts

In [53]:
def get_top_journal_distribution(clusters):
    top_cnt_dict = get_top_journals(clusters)
    total = sum(top_cnt_dict.values())
    percent_dist = {name: (count / total) * 100 for name, count in top_cnt_dict.items()}
    return percent_dist

In [54]:
model,clusters = cluster_sample() #47s no gpu on VM

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 28183.91it/s]
[transformers] RobertaModel LOAD REPORT from: allenai/biomed_roberta_base
Key                       | Status     |  |
--------------------------+------------+--+-
lm_head.layer_norm.bias   | UNEXPECTED |  |
lm_head.bias              | UNEXPECTED |  |
lm_head.decoder.weight    | UNEXPECTED |  |
lm_head.dense.bias        | UNEXPECTED |  |
lm_head.dense.weight      | UNEXPECTED |  |
lm_head.layer_norm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [70]:
model.get_topic_info().head(15)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,60,-1_mice_target_noncoding_physiological,"[mice, target, noncoding, physiological, cache...","[mice, mice, mice]"
1,0,43,0_tissues_seq_dissected_rna,"[tissues, seq, dissected, rna, mrna, disease, ...","[tissues, tissues, tissues]"
2,1,43,1_muscle_muscular__,"[muscle, muscular, , , , , , , , ]","[muscle, muscle, muscle]"
3,2,39,2_type_wt_programs_analysis,"[type, wt, programs, analysis, circadian, prom...","[type, type, type]"
4,3,34,3_dioxide_diversity_sclerosis_resistance,"[dioxide, diversity, sclerosis, resistance, re...","[diversity, increase, resistance]"
5,4,32,4_genes_gene_activitiy_genetic,"[genes, gene, activitiy, genetic, studies, act...","[genes, genes, genes]"
6,5,30,5_skeletal___,"[skeletal, , , , , , , , , ]","[skeletal, skeletal, skeletal]"
7,6,22,6_glucose_metabolisim_fibers_fiber,"[glucose, metabolisim, fibers, fiber, consumpt...","[glucose, glucose, glucose]"
8,7,22,7_variability_overexpressed_expressed_to,"[variability, overexpressed, expressed, to, la...","[variability, variability, variability]"
9,8,21,8_hur_formation_rna_production,"[hur, formation, rna, production, carbon, , , ...","[HuR, HuR, HuR]"
10,9,21,9_h19ko_dusp27_ampk_pgc,"[h19ko, dusp27, ampk, pgc, muhur, ksrp, ko, 1α...","[DUSP27, DUSP27, H19KO]"
11,10,20,10_muscles_mechanisms_observations_conditions,"[muscles, mechanisms, observations, conditions...","[muscles, muscles, muscles]"
12,11,18,11_week_with_speed_normal,"[week, with, speed, normal, higher, energy, pr...","[week, week, week]"
13,12,17,12_cancer_associated_profile_global,"[cancer, associated, profile, global, gap, cap...","[cancer, cancer, associated]"
14,13,16,13_regulation_regulating_factor_,"[regulation, regulating, factor, , , , , , , ]","[regulation, regulation, regulation]"

In [71]:
top_j = get_top_journals(clusters)
jour_dict = get_top_journal_distribution(clusters)
jour_dist = pd.DataFrame(list(get_top_journal_distribution(clusters).items()),columns=['Journal','Percentage'])

In [57]:
jour_dist

     Journal  Percentage
0  GSE100505   48.648649
1  GSE103202   16.216216
2  GSE134241   35.135135

In [58]:
pd.DataFrame(get_top_cluster_distribution(clusters)) #note: includes outliers as -1 index

             -1         0     1     2     3
GSE134241  25.0  15.384615  25.0  60.0  40.0
GSE103202  25.0  30.769231  25.0  10.0   NaN
GSE100505  50.0  53.846154  50.0  30.0  60.0

In [59]:
list(jour_dict.keys())

['GSE100505', 'GSE103202', 'GSE134241']

In [60]:
list(jour_dict.items())

[('GSE100505', 48.64864864864865),
 ('GSE103202', 16.216216216216218),
 ('GSE134241', 35.13513513513514)]

In [61]:
def _plot_dist(dist):
    fig = px.pie(
    names = list(jour_dict.keys()),
    values = list(jour_dict.values()),
   
    title="Percentage Breakdown of Journals",
    )

    fig.show(renderer="browser")

In [62]:
_plot_dist(jour_dist)

In [63]:
def save_cluster_data(clusters, filename="cluster_data.csv"):
    clusters.to_csv(filename, index=False)

In [64]:
save_cluster_data(clusters, filename="COHORT|study=OSD-770|spaceflight=Space_Flight_top10hits_clusters.csv")

In [65]:
def compare_ground_spaceflight(clusters_ground,clusters_spaceflight):
    #see how much the clusters overlap between the two datasets
    #show common clusters, unique clusters, and distribution of journals in each cluster
    

    #create a set of intersection of clusters
    common_clusters = set(clusters_ground["Name"]).intersection(set(clusters_spaceflight["Name"]))
    unique_clusters_ground = set(clusters_ground["Name"]).difference(set(clusters_spaceflight["Name"]))
    unique_clusters_spaceflight = set(clusters_spaceflight["Name"]).difference(set(clusters_ground["Name"]))

    common_journals =   set(clusters_ground["journals"]).intersection(set(clusters_spaceflight["journals"]))
    unique_journals1 = set(clusters_ground["journals"]).difference(set(clusters_spaceflight["journals"]))
    unique_journals2 = set(clusters_spaceflight["journals"]).difference(set(clusters_ground["journals"]))

    #create a dataframe with the information
    comparison_dict ={
        "common_clusters": list(common_clusters),
        "unique_clusters_ground_control": list(unique_clusters_ground),
        "unique_clusters_spaceflight": list(unique_clusters_spaceflight),
        "common_journals": list(common_journals),
        "unique_journals_ground_control": list(unique_journals1),
        "unique_journals_spaceflight": list(unique_journals2)
    }
   
    
                     
                                                



    return comparison_dict

In [66]:
!ls

'COHORT|study=OSD-100|spaceflight=Ground_Control_top10hits_clusters.csv'
'COHORT|study=OSD-100|spaceflight=Space_Flight_top10hits_clusters.csv'
'COHORT|study=OSD-770|spaceflight=Ground Control_top10hits_clusters.csv'
'COHORT|study=OSD-770|spaceflight=Space_Flight_top10hits_clusters.csv'
 cluster_metadata.ipynb
 requirements.txt

In [67]:
import os
print(os.getcwd())

/home/exouser/Desktop/bridge-rna/clustering

In [68]:
ground_file_path = 'COHORT|study=OSD-100|spaceflight=Ground_Control_top10hits_clusters.csv' 
spaceflight_file_path = 'COHORT|study=OSD-100|spaceflight=Space_Flight_top10hits_clusters.csv'



ground_df = pd.read_csv(ground_file_path)
spaceflight_df = pd.read_csv(spaceflight_file_path)

compare_dict = compare_ground_spaceflight(ground_df, spaceflight_df)